### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by sardaukar** [sorgelig/Menu_MIST#1]
I can see the menu, but with other RBF cores on the SD, it's still empty. Do I need to write an INI file?

**Comment by sorgelig** [comment]
Sorry, i don't understand your problem.
Just put all your cores in the root of SD card and it should work.
Make sure files don't have hidden or system attributes.

**Comment by sardaukar** [comment]
I had to upgrade the firmware on the MiST for it to work (it came with a 2015 one). Now it works!
