### ISSUE TITLE
NTSC Support?

### ISSUE THREAD

**Issue by dkerfoot** [sorgelig/Menu_MIST#3]
I'm using a monitor that works well with most NTSC cores, but am getting "Input Not Supported" when I try to load your menu.  Does this support NTSC or just PAL?

**Comment by sorgelig** [comment]
it's hardcoded to pal

**Comment by dkerfoot** [comment]
Thanks for the super fast reply!  I was afraid of that.  Any chance of an NTSC version?

**Comment by sorgelig** [comment]
I have no time for MiST development, sorry.

**Comment by dkerfoot** [comment]
Thank you  .
